const ERROR_CODES = Object.freeze({
  // Auth errors
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  TOKEN_INVALID: "TOKEN_INVALID",
  TOKEN_MISSING: "TOKEN_MISSING",
  REFRESH_TOKEN_EXPIRED: "REFRESH_TOKEN_EXPIRED",
  ACCOUNT_NOT_VERIFIED: "ACCOUNT_NOT_VERIFIED",
  ACCOUNT_BANNED: "ACCOUNT_BANNED",
  ACCOUNT_INACTIVE: "ACCOUNT_INACTIVE",

  // OTP errors
  OTP_EXPIRED: "OTP_EXPIRED",
  OTP_INVALID: "OTP_INVALID",
  OTP_ALREADY_USED: "OTP_ALREADY_USED",

  // User errors
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  PHONE_ALREADY_EXISTS: "PHONE_ALREADY_EXISTS",

  // Doctor errors
  DOCTOR_NOT_FOUND: "DOCTOR_NOT_FOUND",
  DOCTOR_NOT_AVAILABLE: "DOCTOR_NOT_AVAILABLE",

  // Patient errors
  PATIENT_NOT_FOUND: "PATIENT_NOT_FOUND",

  // Appointment errors
  APPOINTMENT_NOT_FOUND: "APPOINTMENT_NOT_FOUND",
  APPOINTMENT_CONFLICT: "APPOINTMENT_CONFLICT",
  APPOINTMENT_ALREADY_CANCELLED: "APPOINTMENT_ALREADY_CANCELLED",
  APPOINTMENT_SLOT_TAKEN: "APPOINTMENT_SLOT_TAKEN",

  // Specialty errors
  SPECIALTY_NOT_FOUND: "SPECIALTY_NOT_FOUND",
  SPECIALTY_ALREADY_EXISTS: "SPECIALTY_ALREADY_EXISTS",

  // Validation
  VALIDATION_ERROR: "VALIDATION_ERROR",

  // General
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
});

module.exports = ERROR_CODES;
